#!/usr/bin/env python3
"""Pack processed CC0 assets into src/assetpack.js (base64, loaded lazily per level by src/assets.js)."""
import json, base64, pathlib, hashlib
import numpy as np
from PIL import Image
ROOT = pathlib.Path(__file__).resolve().parent.parent
A = ROOT / 'assets'
out = ['// GENERATED by tools/build_assets.py — CC0 assets (see docs/CREDITS.md). Do not edit by hand.']
tex = json.loads((A / 'tex' / 'index.json').read_text())
# only pack texture sets the game actually references ('key' / "key" in src/*.js): processed-but-unused sets stay in assets/tex
import re
SRC = ''.join(f.read_text() for f in (ROOT / 'src').glob('*.js') if f.name != 'assetpack.js')
used = {k for k in tex if re.search(r"['\"]" + re.escape(k) + r"['\"]", SRC)}
if set(tex) - used: print('not packed (unreferenced):', ' '.join(sorted(set(tex) - used)))
T = {}
seen = {}
for k, v in sorted(tex.items()):
    if k not in used: continue
    e = {'w': v['w'], 'h': v['h'], 'src': v['src']}
    im = np.asarray(Image.open(A / 'tex' / f'{k}_a.webp').convert('RGB'), dtype=np.float32) / 255.0
    m = (im * im).reshape(-1, 3).mean(0)              # mean of the shader's squared (≈linear) albedo
    e['m'] = [round(float(x), 4) for x in m]; e['l'] = round(float(m @ np.array([0.3, 0.59, 0.11])), 4)
    if v.get('alpha'): e['alpha'] = 1
    for s in 'anr':
        b = (A / 'tex' / f'{k}_{s}.webp').read_bytes()
        hsh = hashlib.sha1(b).hexdigest()
        if hsh in seen: e[s] = '@' + seen[hsh]          # reuse identical image data
        else: seen[hsh] = f'{k}.{s}'; e[s] = base64.b64encode(b).decode()
    T[k] = e
out.append('const ASSET_TEX = ' + json.dumps(T, separators=(',', ':')) + ';')
mdl = A / 'mdl' / 'index.json'
if mdl.exists():
    M = json.loads(mdl.read_text())
    for k, v in M.items():
        v['bin'] = base64.b64encode((A / 'mdl' / v['bin']).read_bytes()).decode()
        for s in ('a', 'n', 'r'):
            if v.get(s): v[s] = base64.b64encode((A / 'mdl' / v[s]).read_bytes()).decode()
    out.append('const ASSET_MDL = ' + json.dumps(M, separators=(',', ':')) + ';')
else: out.append('const ASSET_MDL = {};')
chr_ = A / 'chr' / 'index.json'
if chr_.exists():
    C = json.loads(chr_.read_text())
    for k, v in C.items():
        if v.get('meta'): v['meta'] = json.loads((A / 'chr' / v['meta']).read_text())
        for f in ('bin', 'a', 'n', 'r', 'e', 'anim'):
            if v.get(f): v[f] = base64.b64encode((A / 'chr' / v[f]).read_bytes()).decode()
    out.append('const ASSET_CHR = ' + json.dumps(C, separators=(',', ':')) + ';')
else: out.append('const ASSET_CHR = {};')
js = '\n'.join(out) + '\n'
(ROOT / 'src' / 'assetpack.js').write_text(js)
print('assetpack.js', len(js))
