const path = require('path');
module.exports = async (page) => {
  const out = process.env.BR_QA_OUT, shot = async (name) => { await page.evaluate(() => { window.__BR.DBG.ts = 0; }); await page.waitForTimeout(1200); await page.screenshot({ path: path.join(out, name + '.png') }); await page.evaluate(() => { window.__BR.DBG.ts = 1; }); };
  await page.evaluate(() => { const B = window.__BR; B.G.state = 'title'; B.G.diff = 1; B.goLevel37(null); });
  await page.waitForFunction(() => ['intro', 'play'].includes(window.__BR.G.state) && window.__BR.W37 && window.__BR.W37.pos, null, { timeout: 240000 });
  const a = await page.evaluate(() => { const B = window.__BR; for (let i = 0; i < 400 && B.G.state !== 'play'; i++) B.simStep(0.05); for (let i = 0; i < 30; i++) B.simStep(0.05);
    const LV = B.LV37(); return { st: B.G.state, errs: B.ERRS.n, last: B.ERRS.last, rooms: LV.rooms.length, fh: B.floorY37(B.PL.x, B.PL.z), depth: B.depth37(B.PL.x, B.PL.z), ey: B.G37.ey, cam: B.CAM().position.y }; });
  console.log('A ' + JSON.stringify(a));
  const view = async (name, x, z, yaw, pitch = 0) => { await page.evaluate(([x, z, yaw, pitch]) => { const B = window.__BR, PL = B.PL; PL.x = x; PL.z = z; PL.cell = -1; PL.yaw = yaw; PL.pitch = pitch; PL.fk = 0; for (let i = 0; i < 24; i++) B.simStep(0.05); PL.yaw = yaw; PL.pitch = pitch; B.simStep(0.02); }, [x, z, yaw, pitch]); await shot(name); };
  const C = 3.6;
  await view('v_sh', 35 * C, 28.5 * C, 0.0, 0.0);
  await view('v_arch', 30 * C, 36 * C, -1.57, 0.0);
  await view('v_stair', 37 * C, 31 * C, 1.4, 0.15);
  await view('v_ghost', 61 * C, 66.3 * C, 0.0, 0.0);
  await view('v_sh2', 30 * C, 29 * C, 0.8, 0.0);
  await view('v_well', 35 * C, 14 * C, 0.0, 0.0);
  await view('v_pit', 35 * C, 41 * C, 0.0, 0.0);
  await view('v_hcorr', 34.5 * C, 43.8 * C, 0.0, 0.0);
  await view('v_cab', 24 * C, 37 * C, 3.3, 0.0);
  await view('v_booth', 42.6 * C, 18.5 * C, 1.57, 0.0);
  await view('v_booth2', 44.5 * C, 19 * C, -1.57, 0.0);
  await view('v_plant', 12 * C, 30 * C, 1.57, 0.0);
  await view('v_lobby', 35 * C, 49 * C, 0.15, 0.02);
  await view('v_court', 35 * C, 56 * C, 0.1, 0.05);
  await view('v_hosp', 14 * C, 6.5 * C, 1.57, 0.0);
  await view('v_theatre', 39.5 * C, 4.2 * C, 0.0, 0.0);
  await view('v_plaza', 63 * C, 41.6 * C, 0.1, 0.05);
  await view('v_dome', 62 * C, 53.6 * C, 0.1, 0.0);
  await view('v_staff', 58 * C, 61.5 * C, 1.57, 0.0);
  await view('v_wave', 56 * C, 66.5 * C, 0.0, 0.1);
  const e = await page.evaluate(() => ({ errs: window.__BR.ERRS.n, last: window.__BR.ERRS.last })); console.log('E ' + JSON.stringify(e));
};
