const fs=require('fs');
module.exports=async(page,logs)=>{
const ev=f=>page.evaluate(f),shot=async n=>{await page.waitForTimeout(1000);await page.screenshot({path:process.env.BR_QA_OUT+'/'+n+'.png'});};
await ev(()=>{const B=window.__BR;B.DBG.ts=12;B.DBG.god=true;B.goLevel18(null);});await page.waitForFunction(()=>window.__BR.G.state==='play',null,{timeout:300000});
await ev(()=>{const B=window.__BR;B.DBG.ts=0;B.setPhase18('memories');B.SUBS.q=[];B.SUBS.cur=null;document.getElementById('subs').innerHTML='';document.getElementById('toast').classList.remove('show');});
const pos=async(x,z,yaw,pitch=0)=>page.evaluate(([x,z,yaw,pitch])=>{const B=window.__BR;Object.assign(B.PL,{x,z,yaw,pitch,vx:0,vz:0,hp:100,san:100});B.updateField();B.playerCamera(1/30);B.worldFX18(1/30);B.updateHUD(1/30);},[x,z,yaw,pitch]);
await pos(39.2,69,Math.PI,-0.06);await ev(()=>{const B=window.__BR;B.readNote18('desk');B.simStep(1/30);});await shot('notes_fixed');await ev(()=>{const B=window.__BR;B.SUBS.q=[];B.SUBS.cur=null;document.getElementById('subs').innerHTML='';});
await pos(103,95,0,0);await shot('slides_fixed');
await pos(131.4,77.4,0,0);await ev(()=>{const B=window.__BR,f=B.AI18.fog[0];f.respawn();f.place(131.4,85,Math.PI);f.st='peek';B.PL.flash=true;B.PL.fk=1;B.playerCamera(1/30);f.cull();B.worldFX18(1/30);});await shot('forgotten_clean');
await pos(22,73.8,Math.PI/2,0);await ev(()=>{const B=window.__BR,f=B.AI18.fog[0];f.respawn();f.place(25.2,73.8,-Math.PI/2);f.st='peek';f.cull();B.worldFX18(1/30);});await shot('enemy_staged');
// Export the actual rendered music-box buffer, not a reconstructed approximation.
const audio=await ev(()=>{const b=window.__BR.AU.lull18,a=b.getChannelData(0),out=new Uint8Array(a.length*2),v=new DataView(out.buffer);for(let i=0;i<a.length;i++)v.setInt16(i*2,Math.max(-1,Math.min(1,a[i]))*32767,true);let s='';for(let i=0;i<out.length;i+=8192)s+=String.fromCharCode(...out.subarray(i,i+8192));return {pcm:btoa(s),sr:b.sampleRate,duration:b.duration};});
const pcm=Buffer.from(audio.pcm,'base64'),head=Buffer.alloc(44);head.write('RIFF');head.writeUInt32LE(pcm.length+36,4);head.write('WAVE',8);head.write('fmt ',12);head.writeUInt32LE(16,16);head.writeUInt16LE(1,20);head.writeUInt16LE(1,22);head.writeUInt32LE(audio.sr,24);head.writeUInt32LE(audio.sr*2,28);head.writeUInt16LE(2,32);head.writeUInt16LE(16,34);head.write('data',36);head.writeUInt32LE(pcm.length,40);fs.writeFileSync(process.env.BR_QA_OUT+'/Level18_MusicBox_Preview.wav',Buffer.concat([head,pcm]));logs.push('QA music box '+audio.duration+'s '+audio.sr+'Hz');
await ev(()=>{const B=window.__BR;B.PL.flash=false;B.PL.fk=0;if(B.M18)B.M18.signed=true;for(const d of B.W18.drawings)B.takeDrawing18(d);(B.takeCrayons18 && !B.P18.crayons && B.takeCrayons18()), B.pinDrawings18();   // r6: the door needs crayons before it can be finished
for(let i=0;i<150;i++)B.simStep(1/30);B.SUBS.q=[];B.SUBS.cur=null;document.getElementById('subs').innerHTML='';document.getElementById('toast').classList.remove('show');});
await pos(32,64.8,-Math.PI/2);await shot('door_clean');await pos(36,60.5,Math.PI);await shot('board_clean');
await page.setViewportSize({width:390,height:844});await pos(39.2,69,Math.PI);await ev(()=>{const B=window.__BR;B.readNote18('desk');B.simStep(1/30);document.getElementById('toast').textContent='BRIGHT ROOMS ARE SAFE · KEEP YOUR LIGHT READY';document.getElementById('toast').classList.add('show');});await shot('notes_mobile');logs.push('QA mobile '+JSON.stringify(await ev(()=>{const s=document.getElementById('subs').getBoundingClientRect(),t=document.getElementById('toast').getBoundingClientRect();return {scroll:document.documentElement.scrollWidth,width:innerWidth,subs:[s.x,s.y,s.width,s.height],toast:[t.x,t.y,t.width,t.height]};})));
await ev(()=>{const B=window.__BR;B.win18();for(let i=0;i<180;i++)B.simStep(1/30);});await shot('ending_mobile');logs.push('QA stats fits '+await ev(()=>[...document.querySelectorAll('#endStats b')].every(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth;})));
await page.setViewportSize({width:960,height:540});await shot('ending_final');
};
